name: Validate Code Style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: python3 -m pip install black

      - name: Black style validation
        run: black --check .
